{% set name = "merge-stardist-masks" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/merge_stardist_masks-{{ version }}.tar.gz
  sha256: 024c78a8057dd23389e3e5099c0e51dad3ba2131086e9d1d34b53f0cf5188ed2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.7,<3.10
  run:
    - edt >=2.3.0,<3.0.0
    - numpy >=1.21.0
    - python >=3.7,<3.10
    - stardist >=0.7.3,<0.9.0

test:
  imports:
    - merge_stardist_masks
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/merge-stardist-masks
  summary: Merge Stardist Masks
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
